name: Tag [release]
"on":
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+
jobs:
  tag_release:
    name: Tag [release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Update release description .CHANGELOG.md
        uses: orhun/git-cliff-action@v4
        id: changelog-release
        with:
          config: .cliff.release.toml
          args: --current --strip all
        env:
          OUTPUT: .CHANGELOG.md

      - name: Create Release
        uses: ncipollo/release-action@v1.16.0
        with:
          allowUpdates: true
          draft: false
          makeLatest: true
          name: ${{ github.ref_name }}
          body: ${{ steps.changelog-release.outputs.content }}
          token: ${{ secrets.PAT }}
